 // ************* EXPORT IMAGES ************
export const location = './assets/icons/location.png';
export const burger = './assets/icons/burger.png';
export const arrowDown = './assets/icons/arrow-down.png';
export const arrowLeft = './assets/icons/arrow-left.png';
export const bucket = './assets/icons/bucket.png';
export const comparing = './assets/icons/comparing.png';
export const facebook = './assets/icons/facebook.png';
export const google = './assets/icons/google.png';
export const heart = './assets/icons/heart.png';
export const instagram = './assets/icons/instagram.png';
export const order = './assets/icons/order.png';
export const paintedArrowDown = './assets/icons/painted-arrow-down.png';
export const search = './assets/icons/search.png';
export const searchBlack = './assets/icons/search-black.png';
export const twitter = './assets/icons/twitter.png';
export const user = './assets/icons/user.png';
export const logo = './assets/images/logo.png';
export const iphone = './assets/images/iphone.png';
export const playMarket = './assets/images/play-market.png';
export const appStore = './assets/images/app-store.png';

